### PR TITLE
feat: Add xontrib-broot

### PR DESCRIPTION
**Pull request by bestlem**
It builds but I can't test as that means getting my fork setup as a NUR repo, which seems a bit too much effort.

This uses poetry, note that you don't need the patchPhase you had in xontrib-term-integrations as you can set format = "pyproject";

### CODE REVIEW

**Comment by drmikecrowe** [comment]
@bestlem  -- please also:

- Ensure the tests pass
- Update the top-level README.

I found these useful:

```sh
nix-shell --arg pkgs 'import <nixpkgs> {}' -A xontrib-XXX
# or
nix-build --arg pkgs 'import <nixpkgs> {}' -A xontrib-XXX
```

**Comment by bestlem** [comment]
The issue I think is that the pyproject has xonsh as a runtime dependency.

But in nix use we already have xonsh so isn't that double counting

**Comment by bestlem** [comment]
This is still failing isn't it? So should not be merged.

These are my first real code PRs where I can't test locally - ie replace the released URL by my local one.
Also first nix python change and the packaging is not obvious

**Comment by bestlem** [comment]
I think I have a fix - well past the local build. However as the PR is merged I can't easily pass it to you

Fix is as per contrib-zoxide add a poatPathch to remove xonsh
```
postPatch = ''
      sed -ie "/xonsh.*=/d" pyproject.toml
    '';
```
And remove xonsh from the build-system.

**Comment by drmikecrowe** [comment]
I'll do that. Might be tonight tho

**Pull request merged**
